[package]
name = "beyondCSV"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
arrow = "50.0"
parquet = "50.0"
polars = { version = "0.37", features = ["lazy", "parquet"] }
