/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "csvUpload": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "dynamo": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "easyCSV": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "easyCSVFe": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "tempAuth": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}