/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "createParquetProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "csvUpload": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "dynamo": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "easyCSVFe": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "parqueCreationProcessorQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "regionalRestAPI": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}